### PR TITLE
fix boolean coercion, disable opencollective for CI environments

### PR DESCRIPTION
**Pull request by macjohnny**

### CODE REVIEW

**Comment by macjohnny** [comment]
@znarf could you have a quick look at this PR? it is a tiny change

**Comment by macjohnny** [comment]
e.g. on CircleCI, see https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by macjohnny** [comment]
Travis: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by macjohnny** [comment]
Gitlab: https://docs.gitlab.com/ee/ci/variables/#predefined-environment-variables

**Comment by znarf** [comment]
@macjohnny Thank you for the input.

And thank you for the fix, I only started to look at his code base recently and this is something that I spotted and wanted to fix: https://github.com/opencollective/opencollective-postinstall/pull/14#discussion_r251827158

**Pull request merged**
